exports.ButtonsMapping = {
    GREEN: "MISCBUTTON_2",
    RED: "MISCBUTTON_3",
    YELLOW: "MISCBUTTON_1",
    BLUE: "MISCBUTTON_4",
    ORANGE: "MISCBUTTON_5",
    SELECT: "MISCBUTTON_9",
    START: "MISCBUTTON_10",
    CONSOLE_KEY: "MISCBUTTON_13",
    STRUM: "MISCAXIS_10",
    WHAMMY: "MISCAXIS_3",
}